from core.skill_manager import BaseSkill
from core.firecracker_sandbox import sandbox_manager
from typing import Dict, Any
from agentscope.tool import ToolResponse
from agentscope.message import TextBlock
import json

class GenWebSkill(BaseSkill):
    """
    Skill for generating full-stack web projects using Sandbox environment.
    Supports both LOCAL (shared) and ONLINE (isolated) modes.
    Provides browser automation, file operations, and shell execution.
    """
    
    async def create_fullstack_project(self, project_name: str, tech_stack: str, user_id: str) -> ToolResponse:
        """
        Generates a full-stack project inside a Sandbox environment.
        
        Args:
            project_name (str): Name of the project.
            tech_stack (str): Desired tech stack (e.g., 'Next.js + FastAPI', 'React + Express').
            user_id (str): The ID of the user (injected by system).
            
        Returns:
            ToolResponse: Summary of the generated project and access URLs.
        """
        try:
            # 1. Get or create sandbox for user
            sandbox_info = sandbox_manager.get_sandbox(user_id)
            client = sandbox_manager.get_client(user_id)
            
            # 2. Create project directory
            project_dir = f"{sandbox_info.home_dir}/{project_name}"
            result = client.exec_command(f"mkdir -p {project_dir}")
            
            # 3. Initialize project based on tech stack
            if 'Next.js' in tech_stack or 'next' in tech_stack.lower():
                # Create Next.js project
                init_cmd = f"cd {project_dir} && npx create-next-app@latest . --typescript --tailwind --app --no-src-dir --import-alias '@/*' --yes"
                client.exec_command(init_cmd)
            elif 'React' in tech_stack or 'react' in tech_stack.lower():
                # Create React + Vite project
                init_cmd = f"cd {project_dir} && npm create vite@latest . -- --template react-ts --yes"
                client.exec_command(init_cmd)
            else:
                # Generic npm project
                client.exec_command(f"cd {project_dir} && npm init -y")
            
            # 4. Create README
            readme_content = f"# {project_name}\n\nTech Stack: {tech_stack}\n\nGenerated by LocalManus\n"
            client.write_file(f"{project_dir}/README.md", readme_content)
            
            # 5. Install dependencies (non-blocking)
            client.exec_command(f"cd {project_dir} && npm install || true")
            
            # 6. Get list of created files
            files_result = client.exec_command(f"ls -la {project_dir}")
            files_list = files_result.get('data', {}).get('output', 'Files created')
            
            content = (
                f"✅ Successfully generated project '{project_name}' using {tech_stack}\n\n"
                f"📁 Project Location: {project_dir}\n\n"
                f"🌐 Sandbox URLs:\n"
                f"  - VNC Browser: {sandbox_info.vnc_url}\n"
                f"  - VSCode: {sandbox_info.vscode_url}\n\n"
                f"📋 Files Created:\n{files_list}\n\n"
                f"💡 Next Steps:\n"
                f"  1. cd {project_dir}\n"
                f"  2. npm run dev\n"
                f"  3. Access via VNC browser at {sandbox_info.vnc_url}"
            )
            return ToolResponse(content=[TextBlock(type="text", text=content)])
            
        except Exception as e:
            error_msg = f"❌ Failed to create project: {str(e)}"
            return ToolResponse(content=[TextBlock(type="text", text=error_msg)])

    async def run_shell_command(self, command: str, user_id: str, cwd: str = None) -> ToolResponse:
        """
        Runs a shell command inside the user's sandbox environment.
        
        Args:
            command (str): The shell command to execute.
            user_id (str): The ID of the user.
            cwd (str, optional): Working directory for command execution.
            
        Returns:
            ToolResponse: Command output with exit code.
        """
        try:
            result = sandbox_manager.execute_command(user_id, command, cwd)
            output = result.get('data', {}).get('output', '')
            exit_code = result.get('data', {}).get('exit_code', 0)
            
            if exit_code == 0:
                content = f"✅ Command executed successfully\n\n{output}"
            else:
                content = f"❌ Command failed (exit code: {exit_code})\n\n{output}"
                
            return ToolResponse(content=[TextBlock(type="text", text=content)])
        except Exception as e:
            error_msg = f"❌ Error executing command: {str(e)}"
            return ToolResponse(content=[TextBlock(type="text", text=error_msg)])
    
    async def read_file(self, file_path: str, user_id: str) -> ToolResponse:
        """
        Reads a file from the user's sandbox.
        
        Args:
            file_path (str): Absolute path to the file.
            user_id (str): The ID of the user.
            
        Returns:
            ToolResponse: File content.
        """
        try:
            client = sandbox_manager.get_client(user_id)
            content = client.read_file(file_path)
            response_text = f"📄 File: {file_path}\n\n```\n{content}\n```"
            return ToolResponse(content=[TextBlock(type="text", text=response_text)])
        except Exception as e:
            error_msg = f"❌ Error reading file: {str(e)}"
            return ToolResponse(content=[TextBlock(type="text", text=error_msg)])
    
    async def write_file(self, file_path: str, content: str, user_id: str) -> ToolResponse:
        """
        Writes content to a file in the user's sandbox.
        
        Args:
            file_path (str): Absolute path to the file.
            content (str): Content to write.
            user_id (str): The ID of the user.
            
        Returns:
            ToolResponse: Success confirmation.
        """
        try:
            client = sandbox_manager.get_client(user_id)
            client.write_file(file_path, content)
            response_text = f"✅ Successfully wrote to {file_path}\n\nSize: {len(content)} bytes"
            return ToolResponse(content=[TextBlock(type="text", text=response_text)])
        except Exception as e:
            error_msg = f"❌ Error writing file: {str(e)}"
            return ToolResponse(content=[TextBlock(type="text", text=error_msg)])
    
    async def list_files(self, directory: str, user_id: str) -> ToolResponse:
        """
        Lists files in a directory within the user's sandbox.
        
        Args:
            directory (str): Directory path to list.
            user_id (str): The ID of the user.
            
        Returns:
            ToolResponse: List of files and directories.
        """
        try:
            client = sandbox_manager.get_client(user_id)
            files = client.list_files(directory)
            
            if isinstance(files, list):
                files_text = "\n".join([f"  - {f.get('name', f)}" for f in files[:20]])  # Limit to 20
                response_text = f"📁 Directory: {directory}\n\n{files_text}"
                if len(files) > 20:
                    response_text += f"\n\n... and {len(files) - 20} more files"
            else:
                response_text = f"📁 Directory: {directory}\n\n{files}"
                
            return ToolResponse(content=[TextBlock(type="text", text=response_text)])
        except Exception as e:
            error_msg = f"❌ Error listing directory: {str(e)}"
            return ToolResponse(content=[TextBlock(type="text", text=error_msg)])
    
    async def start_dev_server(self, project_dir: str, user_id: str, port: int = 3000) -> ToolResponse:
        """
        Starts a development server for a web project.
        
        Args:
            project_dir (str): Project directory path.
            user_id (str): The ID of the user.
            port (int): Port to run the server on (default: 3000).
            
        Returns:
            ToolResponse: Server status and access information.
        """
        try:
            sandbox_info = sandbox_manager.get_sandbox(user_id)
            client = sandbox_manager.get_client(user_id)
            
            # Start dev server in background (using nohup or screen)
            start_cmd = f"cd {project_dir} && nohup npm run dev -- --port {port} > dev.log 2>&1 &"
            client.exec_command(start_cmd)
            
            # Wait a moment for server to start
            import asyncio
            await asyncio.sleep(2)
            
            # Check if process is running
            check_cmd = f"lsof -i :{port} || netstat -tuln | grep {port}"
            result = client.exec_command(check_cmd)
            
            response_text = (
                f"🚀 Development server starting...\n\n"
                f"📁 Project: {project_dir}\n"
                f"🌐 Port: {port}\n\n"
                f"Access via:\n"
                f"  - VNC Browser: {sandbox_info.vnc_url}\n"
                f"  - Then open http://localhost:{port} in the sandbox browser\n\n"
                f"📋 Server Status:\n{result.get('data', {}).get('output', 'Starting...')}"
            )
            return ToolResponse(content=[TextBlock(type="text", text=response_text)])
        except Exception as e:
            error_msg = f"❌ Error starting dev server: {str(e)}"
            return ToolResponse(content=[TextBlock(type="text", text=error_msg)])
    
    async def get_sandbox_info(self, user_id: str) -> ToolResponse:
        """
        Gets information about the user's sandbox environment.
        
        Args:
            user_id (str): The ID of the user.
            
        Returns:
            ToolResponse: Sandbox information including URLs and capabilities.
        """
        try:
            sandbox_info = sandbox_manager.get_sandbox(user_id)
            client = sandbox_manager.get_client(user_id)
            
            # Get context
            context = client.get_context()
            
            response_text = (
                f"📦 Sandbox Information\n\n"
                f"🆔 Sandbox ID: {sandbox_info.sandbox_id}\n"
                f"🔧 Mode: {sandbox_info.mode.value}\n"
                f"📁 Home Directory: {sandbox_info.home_dir}\n\n"
                f"🌐 Access URLs:\n"
                f"  - API Base: {sandbox_info.base_url}\n"
                f"  - VNC Browser: {sandbox_info.vnc_url}\n"
                f"  - VSCode Server: {sandbox_info.vscode_url}\n\n"
                f"💻 Capabilities:\n"
                f"  - Shell commands via exec_command\n"
                f"  - File operations (read/write/list)\n"
                f"  - Browser automation via CDP\n"
                f"  - Jupyter Python kernel\n"
                f"  - MCP protocol support\n\n"
                f"📊 Context:\n{json.dumps(context, indent=2)}"
            )
            return ToolResponse(content=[TextBlock(type="text", text=response_text)])
        except Exception as e:
            error_msg = f"❌ Error getting sandbox info: {str(e)}"
            return ToolResponse(content=[TextBlock(type="text", text=error_msg)])
